controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: App\Http\Controller
    type: attribute

admin_controllers:
    prefix: /admin
    resource:
        path: ../src/Http/AdminController/
        namespace: App\Http\AdminController
    type: attribute
