FROM dunglas/frankenphp:php8.4

RUN install-php-extensions \
    intl \
    pdo_sqlite \
    pdo_mysql \
    zip \
    opcache

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
